easy_admin:
    entities:
        # List the entity class name you want to manage
        - Vega\Entity\Answer
        - Vega\Entity\Comment
        - Vega\Entity\Post
        - Vega\Entity\Question
        - Vega\Entity\Tag
        - Vega\Entity\User
    site_name: 'Vega Question Answer System'
